# Generated by Django 3.2 on 2021-04-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_discussion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
