# Generated by Django 3.1.7 on 2021-04-14 18:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_auto_20210414_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='opinion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
